
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caubiehfnakgxyhqldjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhdWJpZWhmbmFrZ3h5aHFsZGpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzEyOTcsImV4cCI6MjA2MTk0NzI5N30.WKV9x1S_LOkzui_ZFQArnfjD3AzwxUWKuRXplVITqBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
