// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxswrhbkqtgamhqkdxma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14c3dyaGJrcXRnYW1ocWtkeG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDA4ODEsImV4cCI6MjA2MzIxNjg4MX0.drIiYFtmQnkyVsGggSkzJMDKJcBY9e685AGQCFFuKpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);